# Site settings
title: Jiatao Gu
email: thomagram@gmail.com
description: academic website
baseurl: ""
url: ""
affiliation: I am a research scientist at Meta AI (FAIR)

# Google analytics ID
google_analytics:

# Location info. (shown in footer)
location: >
  Coordinates: <br/>
  770 Broadway, 7th floor <br/>
  Meta Platform Inc. <br/>
  New York, NY 10003<br/>

# Contact info. (shown in footer)
contact: >
    Contact Jiatao via email: <a href="mailto:thomagram@gmail.com" target="_blank">thomagram@gmail.edu</a> <br/>
#    <br/><a href="/aboutwebsite.html">Use this webpage as a template for your own!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: service
# - name: research
# - name: software
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
